### PR TITLE
Updating the model sync with the dashboard

### PR DESCRIPTION
**Pull request by anurag0511**
Still a WIP, will be updating the further commits to this PR. Would need some more params in the `fit_bexar_mask` script to ensure that the conditions are satisfied for getting the data for the dashboard. For my case, my next commits would involve integrating the geojsons into the main dashboard. And then adding the model in the `get_predictions` file. 
So, the additions that I would like to have are :
+ A `param` for selecting whether we want the trainer to run or not.
+  A 'param' for whether we want to plot or not
+ Return `actives` and `totals` dict in the pipeline method.
+ I am returning the `df` parameter in the `load_data` method since it will be required for the dashboard and would avoid redundant calls to `conflate_data`. 

I have attached the template `fit_bexar_mask` in the commit. But @craymichael you can refactor it in a better way.

### CODE REVIEW

**Comment by anurag0511** [comment]
So, I have integrated the model with the dashboard. The geojsons are also created at the start of the dashboard file. However, I had make some additional changes to the `fit_bexar_mask` script. Do take a look at them once and see how it fits.

**Comment by anurag0511** [comment]
Cleaned the files, made minor edits. However, do take a look at the `fit_bexar_mask` file for the edits. I have added additional argument to the pipeline function, and some parameters to the argparse interface. However, these changes won't affect the default operation of the network.

**Comment by craymichael** [comment]
Finally getting to this today

**Comment by craymichael** [comment]
All merged now, some changes didn't appear to work in the dashboard before so I fixed them (minor cases). Let me know if things look good on your end!

**Pull request merged**
