### PR TITLE
Adding the modular data retriever source

### PR DESCRIPTION
**Pull request by anurag0511**
Updated the source for the data retriever module to make it more readable and modular. Removed some unused code and modified helper functions.

### CODE REVIEW

**Comment by craymichael** [comment]
Ok I am reviewing this today

**Comment by anurag0511** [comment]
Hey zach, did you get a chance to review the PR?

**Comment by craymichael** [comment]
I am actually looking at a it right now - didn't have enough time to finish it yesterday. I'll merge within the hour

**Comment by craymichael** [comment]
Ok it looks fine to me Anurag, I made minor changes and optimizations but generally left everything as-is. I'll merge with dev now and then push my changes later today ideally.

**Pull request merged**
